const subjects=['Philosophie','Littérature / humanités','Philosophie humanités','Histoire','Géographie','SVT','Italien','Anglais','Musique','Informatique','Arts','Sport','Enseignement scientifique','EMC','Méthodologie','Orientation / université'];
const teachers={'Philosophie':'Bateau-Watson','Littérature / humanités':'Merlet, Caron','Philosophie humanités':'Sagniere','Histoire':'Noiret','Géographie':'Noiret','SVT':'Lassale','Italien':'Ditoma','Anglais':'Egron','Musique':'—','Informatique':'—','Arts':'—','Sport':'Chevalier','Enseignement scientifique':'Pirot, Ghenimi, Corvellec','EMC':'Noiret','Méthodologie':'—','Orientation / université':'Mme Burélie'};
const tasks={comprendre:{title:'Comprendre un concept',text:'Construire une explication et tester ta compréhension.',functions:['Comprendre']},reviser:{title:'Réviser',text:'Transformer le cours en rappel actif.',functions:['Réviser','Mémoriser']},rechercher:{title:'Faire une recherche',text:'Trouver, comparer, organiser et citer des sources.',functions:['Rechercher','Vérifier']},presenter:{title:'Faire une présentation',text:'Structurer l’information puis produire un support visuel.',functions:['Présenter','Créer']},organiser:{title:"M’organiser",text:'Centraliser tâches, notes et fichiers.',functions:['Organiser']}};
const advice={
'Philosophie':['Argumenter, problématiser et lire les textes sans déléguer ton jugement.','Cours → notions → problème → thèses → arguments → objections → rédaction → relecture',['ChatGPT','Stanford Encyclopedia of Philosophy','Google Scholar','Google Docs','Anki']],
'Littérature / humanités':['Lire attentivement, contextualiser, interpréter et construire une analyse.','Lecture → annotations → contexte → problématique → plan → rédaction → vérification',['Google Docs','ChatGPT','NotebookLM','LanguageTool','Pinterest']],
'Philosophie humanités':['Relier concepts, textes et contexte historique avec précision.','Cours → corpus → concepts → comparaisons → synthèse critique',['ChatGPT','NotebookLM','Google Scholar','Zotero']],
'Histoire':['Distinguer chronologie, causalité, acteurs, documents et interprétations.','Cours → chronologie → documents → contexte → confrontation des sources → synthèse',['NotebookLM','Google Scholar','Zotero','Anki','YouTube']],
'Géographie':['Passer de la carte ou du territoire à une analyse spatiale argumentée.','Localiser → observer → contextualiser → expliquer les dynamiques spatiales',['Google Earth','Google Scholar','Canva','YouTube']],
'SVT':['Relier observation, modèle, données et conclusion scientifique.','Question → hypothèse → données → modèle → interprétation → conclusion',['NotebookLM','YouTube','GeoGebra','ChatGPT']],
'Italien':['Développer vocabulaire, grammaire, compréhension et production active.','Input → vocabulaire → rappel actif → production → correction → répétition',['Google Translate','Anki','LanguageTool','YouTube','ChatGPT']],
'Anglais':['Développer précision linguistique et compréhension de documents authentiques.','Compréhension → vocabulaire → grammaire en contexte → production → feedback',['Anki','YouTube','LanguageTool','ChatGPT','Google Translate']],
'Musique':['Transformer une idée sonore en composition, production ou performance contrôlée.','Idée → esquisse → arrangement → enregistrement → sound design → mix → export',['Ableton Live','YouTube','Canva','CapCut']],
'Informatique':['Comprendre les systèmes en construisant réellement des choses.','Problème → spécification → prototype → code → test → Git → documentation',['Visual Studio Code','GitHub','ChatGPT','YouTube']],
'Arts':['Développer une intention artistique, des références et une réalisation cohérente.','Références → intention → essais → sélection → réalisation → critique',['Pinterest','Canva','CapCut','ChatGPT']],
'Sport':['Suivre la pratique, comprendre les consignes et progresser régulièrement.','Objectif → séance → pratique → observation → récupération → progression',['YouTube','TickTick']],
'Enseignement scientifique':['Relier modèles, données, calculs et enjeux scientifiques.','Problème → modèle → données → calcul/graphique → interprétation',['GeoGebra','Desmos','YouTube','ChatGPT']],
'EMC':['Analyser une question civique en distinguant faits, valeurs et arguments.','Question → faits → acteurs → valeurs → arguments contradictoires → position',['Google Scholar','ChatGPT','Canva','NotebookLM']],
'Méthodologie':['Construire un système de travail stable plutôt que dépendre de la motivation.','Capturer → prioriser → travailler → vérifier → mémoriser → archiver',['TickTick','Pronote','OneNote','OneDrive','Anki']],
'Orientation / université':['Prendre des décisions d’orientation sur des informations vérifiables.','Explorer → comparer → vérifier prérequis → dossier → échéances → décision',['Google Scholar','GitHub','Canva','Microsoft 365']]
};
const $=s=>document.querySelector(s),grid=$('#tool-grid');
const favorites=new Set(JSON.parse(localStorage.getItem('stbFav')||'[]'));const notes=JSON.parse(localStorage.getItem('stbNotes')||'{}');const recent=JSON.parse(localStorage.getItem('stbRecent')||'[]');
function save(){localStorage.setItem('stbFav',JSON.stringify([...favorites]));localStorage.setItem('stbNotes',JSON.stringify(notes));localStorage.setItem('stbRecent',JSON.stringify(recent))}function tag(x){return `<span class="tag">${x}</span>`}
function render(list){$('#resultCount').textContent=list.length;$('#favCount').textContent=favorites.size;grid.innerHTML=list.length?list.map(t=>`<article class="tool-card" data-id="${t.id}"><button class="star ${favorites.has(t.id)?'on':''}">${favorites.has(t.id)?'★':'☆'}</button><span class="type">${t.type}</span><h3>${t.name}</h3><p>${t.desc}</p><div class="tags">${t.subjects.slice(0,3).map(tag).join('')}${tag(t.access)}</div><small>${t.mastery}</small></article>`).join(''):`<div class="empty">Aucun outil ne correspond à ces filtres.</div>`;grid.querySelectorAll('.tool-card').forEach(c=>c.onclick=e=>{if(!e.target.classList.contains('star'))openTool(c.dataset.id)});grid.querySelectorAll('.star').forEach(b=>b.onclick=e=>{const id=e.currentTarget.closest('.tool-card').dataset.id;favorites.has(id)?favorites.delete(id):favorites.add(id);save();filter()})}
function openTool(id){const t=tools.find(x=>x.id===id);if(!t)return;recent.unshift(id);while(recent.length>8)recent.pop();save();$('#modal').setAttribute('aria-hidden','false');const n=notes[id]||{};$('#modalBody').innerHTML=`<span class="type">${t.type}</span><h2>${t.name}</h2><p>${t.desc}</p><div class="detail-grid"><div><b>Quand l’utiliser</b><p>${t.when}</p></div><div><b>À éviter</b><p>${t.avoid}</p></div><div><b>Professeur(s)</b><p>${t.subjects.map(s=>teachers[s]?`${s} — ${teachers[s]}`:'').filter(Boolean).join('<br>')||'À préciser'}</p></div><div><b>Accès / maîtrise</b><p>${t.access} · ${t.mastery}</p></div></div><label class="field"><b>Cours où je l’utilise</b><input id="courseNote" value="${(n.course||'').replaceAll('"','&quot;')}" placeholder="Ex. dissertation, exposé, laboratoire…"></label><label class="field"><b>Mes notes / astuces</b><textarea id="personalNote" placeholder="Ce qui fonctionne pour moi…">${n.note||''}</textarea></label><div class="modal-actions">${t.url?`<a class="primary" href="${t.url}" target="_blank" rel="noopener">Ouvrir l’outil ↗</a>`:''}<button id="saveNote">Enregistrer</button></div>`;$('#saveNote').onclick=()=>{notes[id]={course:$('#courseNote').value,note:$('#personalNote').value};save();$('#modal').setAttribute('aria-hidden','true')}}
function options(){const ss=[...new Set(tools.flatMap(t=>t.subjects))].filter(x=>x!=='Toutes').sort(),fs=[...new Set(tools.flatMap(t=>t.functions))].sort(),ts=[...new Set(tools.map(t=>t.type))].sort();ss.forEach(x=>$('#subjectFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`));fs.forEach(x=>$('#functionFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`));ts.forEach(x=>$('#typeFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`))}
function filter(){const q=$('#search').value.toLowerCase(),s=$('#subjectFilter').value,f=$('#functionFilter').value,t=$('#typeFilter').value,l=$('#levelFilter').value,a=$('#accessFilter').value,fo=$('#favOnly').checked;render(tools.filter(x=>(!q||`${x.name} ${x.desc} ${x.subjects.join(' ')} ${x.functions.join(' ')} ${x.type}`.toLowerCase().includes(q))&&(!s||x.subjects.includes(s)||x.subjects.includes('Toutes'))&&(!f||x.functions.includes(f))&&(!t||x.type===t)&&(!l||x.levels.includes(l))&&(!a||x.access.includes(a))&&(!fo||favorites.has(x.id))))}
function taskCards(){const tg=$('#task-grid');Object.entries(tasks).forEach(([k,v])=>tg.insertAdjacentHTML('beforeend',`<article class="task" data-task="${k}"><b>${v.title}</b><p>${v.text}</p></article>`));tg.querySelectorAll('.task').forEach(c=>c.onclick=()=>{$('#functionFilter').value=tasks[c.dataset.task].functions[0];filter();location.hash='tools'})}
function subjectCards(){const sg=$('#subject-grid');subjects.forEach((s,i)=>sg.insertAdjacentHTML('beforeend',`<article class="subject" data-subject="${s}"><span>${String(i+1).padStart(2,'0')}</span><h3>${s}</h3><p>${tools.filter(t=>t.subjects.includes(s)||t.subjects.includes('Toutes')).length} outils · ${teachers[s]==='—'?'pas de professeur renseigné':teachers[s]}</p></article>`));sg.querySelectorAll('.subject').forEach(c=>c.onclick=()=>openSubject(c.dataset.subject))}
function openSubject(s){const d=advice[s]||['Espace à personnaliser.','Workflow à construire.',[]],list=tools.filter(t=>t.subjects.includes(s)||t.subjects.includes('Toutes'));$('#subject-page').innerHTML=`<div class="subject-panel"><button class="close-subject">×</button><span class="kicker">${s.toUpperCase()}</span><h3>${s}</h3><p><b>Professeur :</b> ${teachers[s]}</p><p>${d[0]}</p><h4>Workflow recommandé</h4><p>${d[1]}</p><h4>Outils prioritaires</h4><div class="tags">${d[2].map(tag).join('')}</div><h4>Outils disponibles</h4><div class="mini-tools">${list.map(t=>`<button data-id="${t.id}">${favorites.has(t.id)?'★ ':''}${t.name}</button>`).join('')}</div></div>`;$('#subject-page .close-subject').onclick=()=>$('#subject-page').innerHTML='';$('#subject-page').querySelectorAll('.mini-tools button').forEach(b=>b.onclick=()=>openTool(b.dataset.id));$('#subject-page').scrollIntoView({behavior:'smooth',block:'center'})}
function recentSection(){if(!recent.length)return;const list=recent.map(id=>tools.find(t=>t.id===id)).filter(Boolean);const el=document.createElement('section');el.className='section recent-section';el.innerHTML=`<div class="section-head"><div><span class="kicker">00 / HISTORY</span><h2>Récemment utilisés</h2></div><p>Ton historique reste local.</p></div><div class="tool-grid">${list.map(t=>`<article class="tool-card recent-card" data-id="${t.id}"><span class="type">${t.type}</span><h3>${t.name}</h3><p>${t.desc}</p></article>`).join('')}</div>`;$('#missions').after(el);el.querySelectorAll('.recent-card').forEach(c=>c.onclick=()=>openTool(c.dataset.id))}
$('#search').addEventListener('input',filter);['subjectFilter','functionFilter','typeFilter','levelFilter','accessFilter','favOnly'].forEach(id=>$('#'+id).addEventListener('change',filter));document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('#search').value='';$('#functionFilter').value=tasks[b.dataset.task].functions[0];filter();location.hash='tools'});$('#modalClose').onclick=()=>$('#modal').setAttribute('aria-hidden','true');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').setAttribute('aria-hidden','true')};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')$('#modal').setAttribute('aria-hidden','true')});$('#favNav').onclick=()=>{$('#favOnly').checked=true;filter();location.hash='tools'};options();taskCards();subjectCards();recentSection();filter();
