const tools=[
{id:'chatgpt',name:'ChatGPT',type:'IA',desc:'Comprendre, questionner, brainstormer, analyser et structurer.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','Italien','Anglais','Informatique','Arts','EMC','Méthodologie','Orientation / université'],functions:['Comprendre','Écrire','Analyser','Réviser'],levels:['learn','assist','automate','replace'],access:'Personnel',mastery:'Maîtrisé',when:'Débloquer une compréhension, simuler un professeur, produire des questions ou obtenir du feedback.',avoid:'Ne pas lui déléguer une dissertation ou une analyse évaluée sans vérification.',url:'https://chatgpt.com/'},
{id:'notebooklm',name:'NotebookLM',type:'IA / recherche',desc:'Interroger et synthétiser un corpus de sources que tu fournis.',subjects:['Philosophie','Littérature / humanités','Histoire','SVT','EMC','Méthodologie'],functions:['Comprendre','Rechercher','Analyser','Réviser'],levels:['learn','assist','automate','replace'],access:'Personnel',mastery:'À découvrir',when:'Travailler sur un ensemble de cours, PDF ou articles et rester ancré dans tes sources.',avoid:'Ne pas confondre résumé généré et lecture critique.',url:'https://notebooklm.google/'},
{id:'canva',name:'Canva',type:'Création',desc:'Présentations, affiches, schémas et supports visuels.',subjects:['Toutes','Arts','EMC'],functions:['Présenter','Créer'],levels:['assist','automate'],access:'Personnel / école',mastery:'Maîtrisé',when:'Transformer une structure déjà pensée en support visuel.',avoid:'Ne pas commencer par le design avant d'avoir construit l'argument.',url:'https://www.canva.com/'},
{id:'digipad',name:'Digipad',type:'Collaboration',desc:'Mur collaboratif pour collecter, classer et partager des ressources.',subjects:['Toutes'],functions:['Collaborer','Organiser','Rechercher'],levels:['learn','assist'],access:'École',mastery:'Maîtrisé',when:'Brainstorming, collecte de liens et travail de groupe.',avoid:'Ne pas l'utiliser comme archive définitive.',url:'https://digipad.app/'},
{id:'padlet',name:'Padlet',type:'Collaboration',desc:'Mur visuel collaboratif pour organiser des idées et ressources.',subjects:['Toutes'],functions:['Collaborer','Organiser'],levels:['learn','assist'],access:'Personnel / école',mastery:'Maîtrisé',when:'Créer rapidement un espace partagé visuel.',avoid:'Éviter de multiplier Padlet et Digipad pour le même projet.',url:'https://padlet.com/'},
{id:'gdocs',name:'Google Docs',type:'Écriture',desc:'Rédaction et édition collaborative.',subjects:['Philosophie','Littérature / humanités','Histoire','Italien','Anglais'],functions:['Écrire','Collaborer'],levels:['learn','assist'],access:'Personnel / école',mastery:'Maîtrisé',when:'Rédaction à plusieurs, commentaires et historique des versions.',avoid:'Ne pas disperser tes documents entre plusieurs systèmes.',url:'https://docs.google.com/'},
{id:'m365',name:'Microsoft 365',type:'Suite scolaire',desc:'Word, PowerPoint, Excel, OneNote, Teams, Forms, OneDrive et autres outils.',subjects:['Toutes'],functions:['Écrire','Présenter','Organiser','Collaborer','Analyser'],levels:['learn','assist','automate'],access:'École',mastery:'Maîtrisé',when:'Utiliser les services institutionnels et les formats scolaires classiques.',avoid:'Ne pas créer plusieurs copies locales sans stratégie de classement.',url:'https://www.microsoft365.com/'},
{id:'pronote',name:'Pronote',type:'Scolarité',desc:'Emploi du temps, devoirs, notes et informations scolaires.',subjects:['Toutes'],functions:['Organiser'],levels:['learn'],access:'École',mastery:'Maîtrisé',when:'Source de vérité pour les informations scolaires.',avoid:'Ne pas utiliser une application de tâches comme substitut aux échéances officielles.',url:'https://www.index-education.com/fr/logiciel-gestion-vie-scolaire-pronote.php'},
{id:'youtube',name:'YouTube',type:'Ressource',desc:'Cours, conférences, tutoriels, archives et démonstrations.',subjects:['Toutes'],functions:['Comprendre','Rechercher','Réviser'],levels:['learn','assist'],access:'Personnel',mastery:'Maîtrisé',when:'Voir une démonstration ou plusieurs explications d'un même concept.',avoid:'Une vidéo n'est pas automatiquement une source académique.',url:'https://www.youtube.com/'},
{id:'pinterest',name:'Pinterest',type:'Inspiration',desc:'Recherche visuelle et références esthétiques.',subjects:['Arts','Musique','Littérature / humanités'],functions:['Rechercher','Créer'],levels:['learn'],access:'Personnel',mastery:'Maîtrisé',when:'Constituer des références visuelles et des moodboards.',avoid:'Ne pas traiter Pinterest comme une source factuelle.',url:'https://www.pinterest.com/'},
{id:'capcut',name:'CapCut',type:'Vidéo',desc:'Montage vidéo et création de contenus audiovisuels.',subjects:['Arts','EMC','Musique'],functions:['Créer','Présenter'],levels:['assist','automate'],access:'Personnel',mastery:'Maîtrisé',when:'Montage rapide, sous-titres et contenus courts.',avoid:'Pour un projet documentaire complexe, contrôler les automatismes et la cohérence du montage.',url:'https://www.capcut.com/'},
{id:'ableton',name:'Ableton Live',type:'Musique',desc:'Composition, enregistrement, production et sound design.',subjects:['Musique'],functions:['Créer','Enregistrer','Analyser'],levels:['learn','assist','automate'],access:'Déjà acheté',mastery:'Maîtrisé',when:'Composition, production et expérimentation sonore.',avoid:'Ne pas confondre collection de plugins et maîtrise du son.',url:'https://www.ableton.com/'},
{id:'palimpseste',name:'Palimpseste',type:'Scolaire',desc:'Ressource scolaire à documenter selon son usage exact.',subjects:['Toutes'],functions:['Organiser','Rechercher'],levels:['learn','assist'],access:'École',mastery:'À documenter',when:'À préciser selon les usages de tes enseignants.',avoid:'Ne pas attribuer de fonction sans vérifier l'usage réel dans ton établissement.',url:''},
{id:'ticktick',name:'TickTick',type:'Organisation',desc:'Tâches, projets, habitudes et planification.',subjects:['Méthodologie'],functions:['Organiser'],levels:['learn','assist'],access:'Personnel',mastery:'Maîtrisé',when:'Gérer les actions concrètes et les échéances personnelles.',avoid:'Ne pas y recopier toutes les informations déjà présentes dans Pronote.',url:'https://ticktick.com/'},
{id:'translate',name:'Google Translate',type:'Langues',desc:'Traduction et aide à la compréhension linguistique.',subjects:['Italien','Anglais'],functions:['Traduire','Comprendre'],levels:['assist','automate','replace'],access:'Personnel',mastery:'Maîtrisé',when:'Vérifier un mot, comparer une formulation ou comprendre rapidement un passage.',avoid:'Ne pas apprendre une langue en copiant directement une traduction.',url:'https://translate.google.com/'},
{id:'scholar',name:'Google Scholar',type:'Recherche académique',desc:'Recherche de publications scientifiques, livres, thèses et citations.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC','Orientation / université'],functions:['Rechercher','Vérifier'],levels:['learn','assist'],access:'Personnel',mastery:'À découvrir',when:'Point d'entrée général pour repérer une littérature académique.',avoid:'Toujours ouvrir et vérifier la source originale.',url:'https://scholar.google.com/'},
{id:'zotero',name:'Zotero',type:'Recherche académique',desc:'Collecter, organiser, annoter et citer des sources.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC','Orientation / université'],functions:['Rechercher','Organiser','Citer'],levels:['learn','assist','automate'],access:'Personnel',mastery:'À découvrir',when:'Toute recherche qui dépasse quelques sources.',avoid:'Ne pas importer des références sans vérifier leurs métadonnées.',url:'https://www.zotero.org/'},
{id:'openalex',name:'OpenAlex',type:'Recherche académique',desc:'Explorer la littérature scientifique, les auteurs, institutions et citations.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC'],functions:['Rechercher','Vérifier'],levels:['learn','assist'],access:'Personnel',mastery:'À découvrir',when:'Cartographier un sujet et repérer les travaux importants.',avoid:'Ne pas prendre le classement bibliométrique pour un jugement de qualité.',url:'https://openalex.org/'},
{id:'doaj',name:'DOAJ',type:'Recherche académique',desc:'Trouver des revues scientifiques en accès ouvert.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC'],functions:['Rechercher','Vérifier'],levels:['learn'],access:'Personnel',mastery:'À découvrir',when:'Chercher des articles accessibles légalement et gratuitement.',avoid:'Vérifier la qualité de la revue et de l'article.',url:'https://doaj.org/'},
{id:'sep',name:'Stanford Encyclopedia of Philosophy',type:'Philosophie',desc:'Encyclopédie académique de référence pour les concepts et traditions philosophiques.',subjects:['Philosophie','EMC'],functions:['Comprendre','Rechercher','Vérifier'],levels:['learn'],access:'Personnel',mastery:'À découvrir',when:'Première clarification sérieuse d'un concept ou débat philosophique.',avoid:'Ne pas remplacer la lecture des œuvres originales.',url:'https://plato.stanford.edu/'},
{id:'anki',name:'Anki',type:'Mémorisation',desc:'Cartes mémoire et répétition espacée.',subjects:['Italien','Anglais','Philosophie','Histoire','SVT','Enseignement scientifique','EMC'],functions:['Réviser','Mémoriser'],levels:['learn'],access:'Personnel',mastery:'À découvrir',when:'Mémoriser vocabulaire, concepts, dates, définitions et distinctions.',avoid:'Ne pas transformer des raisonnements complexes en cartes trop simplistes.',url:'https://apps.ankiweb.net/'},
{id:'languagetool',name:'LanguageTool',type:'Langues / écriture',desc:'Correction orthographique, grammaticale et stylistique multilingue.',subjects:['Littérature / humanités','Italien','Anglais'],functions:['Écrire','Vérifier','Traduire'],levels:['assist'],access:'Personnel',mastery:'À découvrir',when:'Relire et identifier des erreurs après avoir écrit toi-même.',avoid:'Ne pas laisser l'outil réécrire ta voix.',url:'https://languagetool.org/'},
{id:'geogebra',name:'GeoGebra',type:'Sciences / maths',desc:'Visualisation dynamique de fonctions, géométrie, algèbre et statistiques.',subjects:['SVT','Enseignement scientifique'],functions:['Comprendre','Analyser','Visualiser'],levels:['learn','assist'],access:'Personnel',mastery:'À découvrir',when:'Transformer une relation abstraite en objet manipulable.',avoid:'Ne pas utiliser le résultat sans comprendre le modèle.',url:'https://www.geogebra.org/'},
{id:'desmos',name:'Desmos',type:'Sciences / maths',desc:'Calculatrice graphique pour explorer et visualiser des fonctions.',subjects:['Enseignement scientifique'],functions:['Comprendre','Analyser','Visualiser'],levels:['learn'],access:'Personnel',mastery:'À découvrir',when:'Explorer rapidement une fonction ou une relation.',avoid:'Ne pas substituer le graphe au raisonnement mathématique.',url:'https://www.desmos.com/'},
{id:'vscode',name:'Visual Studio Code',type:'Informatique',desc:'Éditeur de code polyvalent pour apprendre et développer.',subjects:['Informatique'],functions:['Coder','Créer'],levels:['learn','assist','automate'],access:'Personnel',mastery:'Intermédiaire',when:'Coder, expérimenter et développer tes projets web.',avoid:'Ne pas installer des extensions sans comprendre leur rôle.',url:'https://code.visualstudio.com/'},
{id:'github',name:'GitHub',type:'Informatique',desc:'Versionnement, projets, portfolio et collaboration sur du code.',subjects:['Informatique','Orientation / université'],functions:['Coder','Organiser','Créer'],levels:['learn','assist'],access:'Personnel',mastery:'Intermédiaire',when:'Conserver l'historique de tes projets et construire un portfolio public.',avoid:'Ne pas publier de secrets, clés API ou données privées.',url:'https://github.com/'},
{id:'earth',name:'Google Earth',type:'Géographie',desc:'Explorer et visualiser le territoire et les données géographiques.',subjects:['Géographie'],functions:['Comprendre','Visualiser','Rechercher'],levels:['learn','assist'],access:'Personnel',mastery:'À découvrir',when:'Explorer des territoires et construire une intuition spatiale.',avoid:'Ne pas confondre visualisation et analyse géographique.',url:'https://earth.google.com/'},
{id:'onenote',name:'OneNote',type:'Notes',desc:'Carnets numériques pour cours, notes, annotations et organisation.',subjects:['Toutes','Méthodologie'],functions:['Prendre des notes','Organiser','Réviser'],levels:['learn','assist'],access:'École',mastery:'À découvrir',when:'Centraliser des notes de cours structurées.',avoid:'Éviter d'en faire un deuxième TickTick ou un deuxième Drive.',url:'https://www.onenote.com/'},
{id:'onedrive',name:'OneDrive',type:'Fichiers',desc:'Stockage et organisation des documents scolaires.',subjects:['Toutes'],functions:['Organiser','Collaborer'],levels:['learn'],access:'École',mastery:'Maîtrisé',when:'Stockage institutionnel et partage de fichiers.',avoid:'Ne pas multiplier les dossiers sans convention de nommage.',url:'https://www.microsoft.com/microsoft-365/onedrive/online-cloud-storage'}
];
const subjects=['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','Italien','Anglais','Musique','Informatique','Arts','Sport','Enseignement scientifique','EMC','Méthodologie','Orientation / université'];
const tasks={comprendre:{title:'Comprendre un concept',text:'Construire une explication, interroger tes sources et tester ta compréhension.',functions:['Comprendre']},reviser:{title:'Réviser',text:'Transformer le cours en rappels actifs et vérifier ce que tu sais réellement.',functions:['Réviser','Mémoriser']},rechercher:{title:'Faire une recherche',text:'Trouver, comparer, organiser et citer des sources solides.',functions:['Rechercher','Vérifier']},presenter:{title:'Faire une présentation',text:'Structurer l’information puis produire un support visuel.',functions:['Présenter','Créer']},organiser:{title:"M'organiser",text:'Centraliser les tâches, notes et fichiers sans multiplier les systèmes.',functions:['Organiser']}};
const $=s=>document.querySelector(s),grid=$('#tool-grid'),favorites=new Set(JSON.parse(localStorage.getItem('studentToolboxFavorites')||'[]'));
function tag(x){return `<span class="tag">${x}</span>`}
function render(list){$('#resultCount').textContent=list.length;$('#favCount').textContent=favorites.size;grid.innerHTML=list.length?list.map(t=>`<article class="tool-card" data-id="${t.id}"><button class="fav ${favorites.has(t.id)?'active':''}" title="Favori" aria-label="Favori">${favorites.has(t.id)?'★':'☆'}</button><span class="type">${t.type}</span><h3>${t.name}</h3><p>${t.desc}</p><div class="tags">${t.subjects.slice(0,3).map(tag).join('')}${tag(t.mastery)}</div></article>`).join(''):`<div class="empty">Aucun outil ne correspond à ces filtres.</div>`;grid.querySelectorAll('.tool-card').forEach(c=>{c.onclick=e=>{if(e.target.closest('.fav'))return;openTool(c.dataset.id)};c.querySelector('.fav').onclick=e=>{e.stopPropagation();toggleFav(c.dataset.id)}})}
function options(){const ss=[...new Set(tools.flatMap(t=>t.subjects))].filter(x=>x!=='Toutes').sort(),fs=[...new Set(tools.flatMap(t=>t.functions))].sort(),ts=[...new Set(tools.map(t=>t.type))].sort();ss.forEach(x=>$('#subjectFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`));fs.forEach(x=>$('#functionFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`));ts.forEach(x=>$('#typeFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`))}
function filter(){const q=$('#search').value.toLowerCase(),s=$('#subjectFilter').value,f=$('#functionFilter').value,t=$('#typeFilter').value,l=$('#levelFilter').value,a=$('#accessFilter').value,fo=$('#favOnly').checked;render(tools.filter(x=>(!q||`${x.name} ${x.desc} ${x.subjects.join(' ')} ${x.functions.join(' ')} ${x.type}`.toLowerCase().includes(q))&&(!s||x.subjects.includes(s)||x.subjects.includes('Toutes'))&&(!f||x.functions.includes(f))&&(!t||x.type===t)&&(!l||x.levels.includes(l))&&(!a||x.access.includes(a))&&(!fo||favorites.has(x.id))))}
function toggleFav(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('studentToolboxFavorites',JSON.stringify([...favorites]));filter()}
function openTool(id){const t=tools.find(x=>x.id===id);if(!t)return;$('#modalBody').innerHTML=`<div class="detail"><span class="detail-kicker">${t.type}</span><h2>${t.name}</h2><p>${t.desc}</p><div class="detail-section"><h4>Meilleur usage</h4><p>${t.when}</p></div><div class="detail-section"><h4>À éviter</h4><p>${t.avoid}</p></div><div class="detail-section"><h4>Dans ton système</h4><div class="tags">${tag('Matières : '+t.subjects.slice(0,5).join(' · '))}${tag('Accès : '+t.access)}${tag('Maîtrise : '+t.mastery)}</div></div><div class="detail-section"><h4>IA / pédagogie</h4><p>${t.levels.includes('learn')?'🟢 Apprendre ':''}${t.levels.includes('assist')?'🟡 Assister ':''}${t.levels.includes('automate')?'🟠 Automatiser ':''}${t.levels.includes('replace')?'🔴 Remplacer':''}</p></div>${t.url?`<div class="detail-section detail-links"><a href="${t.url}" target="_blank" rel="noopener">Ouvrir le site ↗</a></div>`:''}</div>`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function taskCards(){const tg=$('#task-grid');Object.entries(tasks).forEach(([k,v])=>tg.insertAdjacentHTML('beforeend',`<article class="task" data-task="${k}"><b>${v.title}</b><p>${v.text}</p></article>`));tg.querySelectorAll('.task').forEach(c=>c.onclick=()=>{$('#functionFilter').value=tasks[c.dataset.task].functions[0];filter();location.hash='tools'})}
function subjectCards(){const sg=$('#subject-grid');subjects.forEach((s,i)=>sg.insertAdjacentHTML('beforeend',`<article class="subject" data-subject="${s}"><span>${String(i+1).padStart(2,'0')}</span><h3>${s}</h3><p>${tools.filter(t=>t.subjects.includes(s)||t.subjects.includes('Toutes')).length} outils</p></article>`));sg.querySelectorAll('.subject').forEach(c=>c.onclick=()=>{$('#subjectFilter').value=c.dataset.subject;filter();location.hash='tools'})}
$('#search').addEventListener('input',filter);['subjectFilter','functionFilter','typeFilter','levelFilter','accessFilter','favOnly'].forEach(id=>$('#'+id).addEventListener('change',filter));document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('#search').value='';$('#functionFilter').value=tasks[b.dataset.task].functions[0];filter();location.hash='tools'});$('#modalClose').onclick=()=>{$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')};$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modalClose').click()};$('#favNav').onclick=()=>{$('#favOnly').checked=true;filter();location.hash='tools'};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')$('#modalClose').click()});options();taskCards();subjectCards();render(tools);
