const tools=[
{name:'ChatGPT',type:'IA',desc:'Comprendre, questionner, brainstormer, analyser et structurer.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','Italien','Anglais','Informatique','Arts','EMC','Méthodologie','Orientation / université'],functions:['Comprendre','Écrire','Analyser','Réviser'],levels:['learn','assist','automate','replace'],access:'Personnel'},
{name:'NotebookLM',type:'IA / recherche',desc:'Interroger et synthétiser un corpus de sources que tu fournis.',subjects:['Philosophie','Littérature / humanités','Histoire','SVT','EMC','Méthodologie'],functions:['Comprendre','Rechercher','Analyser','Réviser'],levels:['learn','assist','automate','replace'],access:'Personnel'},
{name:'Canva',type:'Création',desc:'Présentations, affiches, schémas et supports visuels.',subjects:['Toutes','Arts','EMC'],functions:['Présenter','Créer'],levels:['assist','automate'],access:'Personnel / école'},
{name:'Digipad',type:'Collaboration',desc:'Mur collaboratif pour collecter, classer et partager des ressources.',subjects:['Toutes'],functions:['Collaborer','Organiser','Rechercher'],levels:['learn','assist'],access:'Web / école'},
{name:'Padlet',type:'Collaboration',desc:'Mur visuel collaboratif pour organiser des idées et ressources.',subjects:['Toutes'],functions:['Collaborer','Organiser'],levels:['learn','assist'],access:'Personnel / école'},
{name:'Google Docs',type:'Écriture',desc:'Rédaction et édition collaborative.',subjects:['Philosophie','Littérature / humanités','Histoire','Italien','Anglais'],functions:['Écrire','Collaborer'],levels:['learn','assist'],access:'Personnel / école'},
{name:'Microsoft 365',type:'Suite scolaire',desc:'Word, PowerPoint, Excel, OneNote, Teams, Forms, OneDrive et autres outils.',subjects:['Toutes'],functions:['Écrire','Présenter','Organiser','Collaborer','Analyser'],levels:['learn','assist','automate'],access:'CIMF → Microsoft 365'},
{name:'Pronote',type:'Scolarité',desc:'Emploi du temps, devoirs, notes et informations scolaires.',subjects:['Toutes'],functions:['Organiser'],levels:['learn'],access:'CIMF → Pronote'},
{name:'YouTube',type:'Ressource',desc:'Cours, conférences, tutoriels, archives et démonstrations.',subjects:['Toutes'],functions:['Comprendre','Rechercher','Réviser'],levels:['learn','assist'],access:'Personnel'},
{name:'Pinterest',type:'Inspiration',desc:'Recherche visuelle et références esthétiques.',subjects:['Arts','Musique','Littérature / humanités'],functions:['Rechercher','Créer'],levels:['learn'],access:'Personnel'},
{name:'CapCut',type:'Vidéo',desc:'Montage vidéo et création de contenus audiovisuels.',subjects:['Arts','EMC','Musique'],functions:['Créer','Présenter'],levels:['assist','automate'],access:'Personnel'},
{name:'Ableton Live',type:'Musique',desc:'Composition, enregistrement, production et sound design.',subjects:['Musique'],functions:['Créer','Enregistrer','Analyser'],levels:['learn','assist','automate'],access:'Déjà acheté'},
{name:'Palimpseste',type:'Scolaire',desc:'Ressource scolaire à documenter selon son usage exact.',subjects:['Toutes'],functions:['Organiser','Rechercher'],levels:['learn','assist'],access:'École'},
{name:'TickTick',type:'Organisation',desc:'Tâches, projets, habitudes et planification.',subjects:['Méthodologie'],functions:['Organiser'],levels:['learn','assist'],access:'Personnel'},
{name:'Google Translate',type:'Langues',desc:'Traduction et aide à la compréhension linguistique.',subjects:['Italien','Anglais'],functions:['Traduire','Comprendre'],levels:['assist','automate','replace'],access:'Personnel'},
{name:'Google Scholar',type:'Recherche académique',desc:'Recherche de publications scientifiques, livres, thèses et citations.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC','Orientation / université'],functions:['Rechercher','Vérifier'],levels:['learn','assist'],access:'Web'},
{name:'Zotero',type:'Recherche académique',desc:'Collecter, organiser, annoter et citer des sources.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC','Orientation / université'],functions:['Rechercher','Organiser','Citer'],levels:['learn','assist','automate'],access:'Web / ordinateur'},
{name:'OpenAlex',type:'Recherche académique',desc:'Explorer la littérature scientifique, les auteurs, institutions et citations.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC'],functions:['Rechercher','Vérifier'],levels:['learn','assist'],access:'Web'},
{name:'DOAJ',type:'Recherche académique',desc:'Trouver des revues scientifiques en accès ouvert.',subjects:['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','EMC'],functions:['Rechercher','Vérifier'],levels:['learn'],access:'Web'},
{name:'Stanford Encyclopedia of Philosophy',type:'Philosophie',desc:'Encyclopédie académique de référence pour les concepts et traditions philosophiques.',subjects:['Philosophie','EMC'],functions:['Comprendre','Rechercher','Vérifier'],levels:['learn'],access:'Web'},
{name:'Anki',type:'Mémorisation',desc:'Cartes mémoire et répétition espacée.',subjects:['Italien','Anglais','Philosophie','Histoire','SVT','Enseignement scientifique','EMC'],functions:['Réviser','Mémoriser'],levels:['learn'],access:'Ordinateur / web'},
{name:'LanguageTool',type:'Langues / écriture',desc:'Correction orthographique, grammaticale et stylistique multilingue.',subjects:['Littérature / humanités','Italien','Anglais'],functions:['Écrire','Vérifier','Traduire'],levels:['assist'],access:'Web'},
{name:'GeoGebra',type:'Sciences / maths',desc:'Visualisation dynamique de fonctions, géométrie, algèbre et statistiques.',subjects:['SVT','Enseignement scientifique'],functions:['Comprendre','Analyser','Visualiser'],levels:['learn','assist'],access:'Web'},
{name:'Desmos',type:'Sciences / maths',desc:'Calculatrice graphique pour explorer et visualiser des fonctions.',subjects:['Enseignement scientifique'],functions:['Comprendre','Analyser','Visualiser'],levels:['learn'],access:'Web'},
{name:'Visual Studio Code',type:'Informatique',desc:'Éditeur de code polyvalent pour apprendre et développer.',subjects:['Informatique'],functions:['Coder','Créer'],levels:['learn','assist','automate'],access:'Ordinateur'},
{name:'GitHub',type:'Informatique',desc:'Versionnement, projets, portfolio et collaboration sur du code.',subjects:['Informatique','Orientation / université'],functions:['Coder','Organiser','Créer'],levels:['learn','assist'],access:'Web / ordinateur'},
{name:'Google Earth',type:'Géographie',desc:'Explorer et visualiser le territoire et les données géographiques.',subjects:['Géographie'],functions:['Comprendre','Visualiser','Rechercher'],levels:['learn','assist'],access:'Web'},
{name:'OneNote',type:'Notes',desc:'Carnets numériques pour cours, notes, annotations et organisation.',subjects:['Toutes','Méthodologie'],functions:['Prendre des notes','Organiser','Réviser'],levels:['learn','assist'],access:'CIMF → Microsoft 365'},
{name:'OneDrive',type:'Fichiers',desc:'Stockage et organisation des documents scolaires.',subjects:['Toutes'],functions:['Organiser','Collaborer'],levels:['learn'],access:'CIMF → Microsoft 365'}
];
const subjects=['Philosophie','Littérature / humanités','Histoire','Géographie','SVT','Italien','Anglais','Musique','Informatique','Arts','Sport','Enseignement scientifique','EMC','Méthodologie','Orientation / université'];
const tasks={comprendre:{title:'Comprendre un concept',text:'Construire une explication, interroger tes sources et tester ta compréhension.',functions:['Comprendre']},reviser:{title:'Réviser',text:'Transformer le cours en rappels actifs et vérifier ce que tu sais réellement.',functions:['Réviser','Mémoriser']},rechercher:{title:'Faire une recherche',text:'Trouver, comparer, organiser et citer des sources solides.',functions:['Rechercher','Vérifier']},presenter:{title:'Faire une présentation',text:'Structurer l'information et produire un support visuel clair.',functions:['Présenter','Créer']},organiser:{title:"M'organiser",text:'Centraliser les tâches, notes et fichiers au lieu de multiplier les systèmes.',functions:['Organiser']}};
const $=s=>document.querySelector(s);const grid=$('#tool-grid');
function tag(x){return `<span class="tag">${x}</span>`}function render(list){grid.innerHTML=list.length?list.map(t=>`<article class="tool-card"><span class="type">${t.type}</span><h3>${t.name}</h3><p>${t.desc}</p><div class="tags">${t.subjects.slice(0,3).map(tag).join('')}${tag(t.access)}</div></article>`).join(''):`<div class="empty">Aucun outil ne correspond à ces filtres.</div>`}
function options(){const ss=[...new Set(tools.flatMap(t=>t.subjects))].filter(x=>x!=='Toutes').sort();const fs=[...new Set(tools.flatMap(t=>t.functions))].sort();const ts=[...new Set(tools.map(t=>t.type))].sort();ss.forEach(x=>$('#subjectFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`));fs.forEach(x=>$('#functionFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`));ts.forEach(x=>$('#typeFilter').insertAdjacentHTML('beforeend',`<option>${x}</option>`))}
function filter(){const q=$('#search').value.toLowerCase();const s=$('#subjectFilter').value,f=$('#functionFilter').value,t=$('#typeFilter').value,l=$('#levelFilter').value;render(tools.filter(x=>(!q||`${x.name} ${x.desc} ${x.subjects.join(' ')} ${x.functions.join(' ')}`.toLowerCase().includes(q))&&(!s||x.subjects.includes(s)||x.subjects.includes('Toutes'))&&(!f||x.functions.includes(f))&&(!t||x.type===t)&&(!l||x.levels.includes(l))))}
function taskCards(){const tg=$('#task-grid');Object.entries(tasks).forEach(([k,v])=>tg.insertAdjacentHTML('beforeend',`<article class="task" data-task="${k}"><b>${v.title}</b><p>${v.text}</p></article>`));tg.querySelectorAll('.task').forEach(c=>c.onclick=()=>{const v=tasks[c.dataset.task];$('#functionFilter').value=v.functions[0];filter();location.hash='tools'})}
function subjectCards(){const sg=$('#subject-grid');subjects.forEach((s,i)=>sg.insertAdjacentHTML('beforeend',`<article class="subject" data-subject="${s}"><span>${String(i+1).padStart(2,'0')}</span><h3>${s}</h3><p>${tools.filter(t=>t.subjects.includes(s)||t.subjects.includes('Toutes')).length} outils dans la base</p></article>`));sg.querySelectorAll('.subject').forEach(c=>c.onclick=()=>{$('#subjectFilter').value=c.dataset.subject;filter();location.hash='tools'})}
$('#search').addEventListener('input',filter);['subjectFilter','functionFilter','typeFilter','levelFilter'].forEach(id=>$('#'+id).addEventListener('change',filter));document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('#search').value='';const v=tasks[b.dataset.task];$('#functionFilter').value=v.functions[0];filter();location.hash='tools'});options();taskCards();subjectCards();render(tools);
